/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Readiness */
        get: operations["check_readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/similar/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find Similar */
        get: operations["find_similar_search_similar__image_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Images */
        get: operations["list_images_images_get"];
        put?: never;
        /** Ingest Images */
        post: operations["ingest_images_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Image */
        post: operations["upload_image_images_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image */
        get: operations["get_image_images__image_id__get"];
        put?: never;
        post?: never;
        /** Delete Image */
        delete: operations["delete_image_images__image_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Job */
        delete: operations["cancel_job_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/rebuild-index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Rebuild Index */
        post: operations["trigger_rebuild_index_jobs_rebuild_index_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/indexes/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Index Versions */
        get: operations["list_index_versions_jobs_indexes_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_sources__source_id__get"];
        put?: never;
        post?: never;
        /** Delete Source */
        delete: operations["delete_source_sources__source_id__delete"];
        options?: never;
        head?: never;
        /** Update Source */
        patch: operations["update_source_sources__source_id__patch"];
        trace?: never;
    };
    "/sources/{source_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Source Run */
        post: operations["trigger_source_run_sources__source_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Source */
        post: operations["retry_source_sources__source_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Source Run */
        post: operations["retry_source_run_sources__source_id__runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}/items/{item_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Source Item */
        post: operations["retry_source_item_sources__source_id__items__item_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Source Items */
        get: operations["list_source_items_sources__source_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{source_id}/runs/{run_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Run Items */
        get: operations["list_run_items_sources__source_id__runs__run_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Ingestion */
        get: operations["list_ingestion_ingestion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/{ingest_url_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion Attempt */
        get: operations["get_ingestion_attempt_ingestion__ingest_url_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingestion/{ingest_url_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion Logs */
        get: operations["get_ingestion_logs_ingestion__ingest_url_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiErrorResponse */
        ApiErrorResponse: {
            /**
             * Detail
             * @description Human-readable error detail
             */
            detail: string;
        };
        /** Body_upload_image_images_upload_post */
        Body_upload_image_images_upload_post: {
            /** File */
            file: string;
            /** Dataset */
            dataset?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** CreateSourceRequest */
        CreateSourceRequest: {
            /**
             * Name
             * @description Unique (among live Sources) display name
             */
            name: string;
            /**
             * Adapter Key
             * @description Adapter the system supports, e.g. 'meme_api'
             */
            adapter_key: string;
            adapter_config: components["schemas"]["MemeApiAdapterConfig"];
            /** Dataset */
            dataset?: string | null;
            /** Schedule Cron */
            schedule_cron?: string | null;
            /**
             * Schedule Timezone
             * @default UTC
             */
            schedule_timezone: string;
            /** Max Items Per Run */
            max_items_per_run?: number | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * DuplicateReason
         * @enum {string}
         */
        DuplicateReason: "SOURCE_SEEN" | "SHA256" | "PHASH";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description Service health state
             */
            status: string;
        };
        /**
         * ImageIngestRequest
         * @example {
         *       "dataset": "my-collection",
         *       "tags": [
         *         "funny",
         *         "cats"
         *       ],
         *       "urls": [
         *         "https://example.com/meme1.jpg",
         *         "https://example.com/meme2.png"
         *       ]
         *     }
         */
        ImageIngestRequest: {
            /**
             * Urls
             * @description List of image URLs to ingest
             */
            urls: string[];
            /**
             * Tags
             * @description Tags to apply
             */
            tags?: string[];
            /**
             * Dataset
             * @description Dataset name for organization
             */
            dataset?: string | null;
            /**
             * Callback Url
             * @description Webhook URL to call when processing completes
             */
            callback_url?: string | null;
        };
        /** ImageIngestResponse */
        ImageIngestResponse: {
            /**
             * Job Id
             * @description Job ID for tracking progress
             */
            job_id: string;
            /**
             * Queued
             * @description Number of images queued
             */
            queued: number;
            /**
             * Duplicates
             * @description Number of duplicate URLs in request
             * @default 0
             */
            duplicates: number;
            /**
             * Message
             * @description Status message
             */
            message: string;
        };
        /** ImageListResponse */
        ImageListResponse: {
            /** Images */
            images: components["schemas"]["ImageResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Has More */
            has_more: boolean;
        };
        /** ImageResponse */
        ImageResponse: {
            /** Id */
            id: number;
            /** Sha256 */
            sha256: string;
            /** Url */
            url?: string | null;
            /** S3 Key */
            s3_key?: string | null;
            /** Dataset */
            dataset?: string | null;
            /** Width */
            width?: number | null;
            /** Height */
            height?: number | null;
            /** Format */
            format?: string | null;
            /** Phash */
            phash?: string | null;
            /** File Size */
            file_size?: number | null;
            status: components["schemas"]["ImageStatus"];
            /** Ocr Status */
            ocr_status?: string | null;
            /** Caption Status */
            caption_status?: string | null;
            /** Embed Status */
            embed_status?: string | null;
            /** Ocr Model */
            ocr_model?: string | null;
            /** Caption Model */
            caption_model?: string | null;
            /** Embed Model */
            embed_model?: string | null;
            /** Embed Dim */
            embed_dim?: number | null;
            /** Embed S3 Key */
            embed_s3_key?: string | null;
            /** Caption */
            caption?: string | null;
            /** Ocr Text */
            ocr_text?: string | null;
            /** Tags */
            tags?: string[];
            /** Created At */
            created_at?: string | null;
        };
        /**
         * ImageStatus
         * @enum {string}
         */
        ImageStatus: "pending" | "downloading" | "scanning" | "annotating" | "embedding" | "done" | "failed";
        /** IndexVersionResponse */
        IndexVersionResponse: {
            /** Version */
            version: string;
            /** Embed Model */
            embed_model?: string | null;
            /** Index Type */
            index_type?: string | null;
            /** Num Vectors */
            num_vectors?: number | null;
            /** Dimension */
            dimension?: number | null;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at?: string | null;
        };
        /** IndexVersionsResponse */
        IndexVersionsResponse: {
            /** Versions */
            versions: components["schemas"]["IndexVersionResponse"][];
        };
        /** IngestJobResult */
        IngestJobResult: {
            /** Processed */
            processed: number;
            /** Failed */
            failed: number;
            /** Duplicates */
            duplicates: number;
        };
        /**
         * IngestOutcome
         * @enum {string}
         */
        IngestOutcome: "ingested" | "deduped" | "failed" | "in_flight";
        /**
         * IngestStage
         * @enum {string}
         */
        IngestStage: "QUEUED" | "DOWNLOADING" | "PROCESSING" | "ANNOTATING" | "EMBEDDING" | "COMPLETE" | "DEDUPED";
        /** IngestionDetailResponse */
        IngestionDetailResponse: {
            /** Ingest Url Id */
            ingest_url_id: number;
            /** Url */
            url: string;
            /** Job Id */
            job_id: string;
            /** Source Run Id */
            source_run_id: number | null;
            /** Source Id */
            source_id: number | null;
            /** Source Name */
            source_name: string | null;
            trigger: components["schemas"]["SourceRunTrigger"];
            stage: components["schemas"]["IngestStage"];
            status: components["schemas"]["ProcessingStatus"];
            outcome: components["schemas"]["IngestOutcome"];
            duplicate_reason: components["schemas"]["DuplicateReason"] | null;
            /** Duplicate Of Image Id */
            duplicate_of_image_id: number | null;
            /** Resolved Image Id */
            resolved_image_id: number | null;
            /** Dataset */
            dataset: string | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Stage Updated At */
            stage_updated_at: string | null;
            /** Image Id */
            image_id: number | null;
        };
        /** IngestionListResponse */
        IngestionListResponse: {
            /** Rows */
            rows: components["schemas"]["IngestionRowResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** IngestionLogEntryResponse */
        IngestionLogEntryResponse: {
            /** Time */
            time: string;
            /** Level */
            level?: string | null;
            /** Event */
            event?: string | null;
            /** Activity Name */
            activity_name?: string | null;
            /** Step */
            step?: string | null;
            /** Outcome */
            outcome?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error */
            error?: string | null;
            /** Attempt */
            attempt?: number | null;
            /** Workflow Id */
            workflow_id?: string | null;
        };
        /** IngestionLogsResponse */
        IngestionLogsResponse: {
            /** Available */
            available: boolean;
            /** Workflow Id */
            workflow_id?: string | null;
            /** Entries */
            entries: components["schemas"]["IngestionLogEntryResponse"][];
        };
        /** IngestionRowResponse */
        IngestionRowResponse: {
            /** Ingest Url Id */
            ingest_url_id: number;
            /** Url */
            url: string;
            /** Job Id */
            job_id: string;
            /** Source Run Id */
            source_run_id: number | null;
            /** Source Id */
            source_id: number | null;
            /** Source Name */
            source_name: string | null;
            trigger: components["schemas"]["SourceRunTrigger"];
            stage: components["schemas"]["IngestStage"];
            status: components["schemas"]["ProcessingStatus"];
            outcome: components["schemas"]["IngestOutcome"];
            duplicate_reason: components["schemas"]["DuplicateReason"] | null;
            /** Duplicate Of Image Id */
            duplicate_of_image_id: number | null;
            /** Resolved Image Id */
            resolved_image_id: number | null;
            /** Dataset */
            dataset: string | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Stage Updated At */
            stage_updated_at: string | null;
        };
        /**
         * IngestionView
         * @enum {string}
         */
        IngestionView: "live" | "completed" | "failed" | "all";
        /** JobListResponse */
        JobListResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobResponse"][];
            /** Total */
            total: number;
        };
        /** JobResponse */
        JobResponse: {
            /**
             * Id
             * @description Unique job ID
             */
            id: string;
            /** @description Job type */
            type: components["schemas"]["JobType"];
            /** @description Current status */
            status: components["schemas"]["JobStatus"];
            /**
             * Progress
             * @description Progress percentage (0-100)
             * @default 0
             */
            progress: number;
            /**
             * Message
             * @description Status message or error
             */
            message?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** @description Job result data */
            result?: components["schemas"]["JobResult"] | null;
        };
        JobResult: components["schemas"]["IngestJobResult"] | components["schemas"]["RebuildJobResult"] | components["schemas"]["RawJobResult"] | {
            [key: string]: components["schemas"]["JsonValue"];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "CANCELED";
        /**
         * JobType
         * @enum {string}
         */
        JobType: "ingest" | "rebuild_index";
        JsonValue: unknown;
        /** MemeApiAdapterConfig */
        MemeApiAdapterConfig: {
            /** Subreddits */
            subreddits: string[];
            /** Max Items Per Run */
            max_items_per_run?: number | null;
        };
        /** MemeApiRawMetadata */
        MemeApiRawMetadata: {
            /** Author */
            author?: string | null;
            /** Title */
            title?: string | null;
            /** Ups */
            ups?: number | null;
            /** Subreddit */
            subreddit?: string | null;
            /** Preview */
            preview?: string | string[] | null;
            /** Postlink */
            postLink?: string | null;
        };
        /**
         * ProcessingStatus
         * @enum {string}
         */
        ProcessingStatus: "PENDING" | "RUNNING" | "DONE" | "FAILED";
        /** RateLimitErrorResponse */
        RateLimitErrorResponse: {
            /**
             * Detail
             * @description Human-readable error detail
             */
            detail: string;
            /**
             * Retry After
             * @description Rate limit retry hint
             */
            retry_after: string;
        };
        /** RawJobResult */
        RawJobResult: {
            /** Raw */
            raw: string;
        };
        /** RebuildIndexRequest */
        RebuildIndexRequest: {
            /**
             * Force
             * @description Force full rebuild even if incremental is possible
             * @default false
             */
            force: boolean;
            /**
             * Model Name
             * @description Override embedding model (triggers full rebuild)
             */
            model_name?: string | null;
        };
        /** RebuildJobResult */
        RebuildJobResult: {
            /** Version */
            version: string;
            /** Num Vectors */
            num_vectors: number;
            /** Dimension */
            dimension: number;
            /** Removed Versions */
            removed_versions: string[];
            /** Text Num Vectors */
            text_num_vectors: number | null;
        };
        /** RetryResponse */
        RetryResponse: {
            /** Job Id */
            job_id: string;
            /** Workflow Id */
            workflow_id: string;
            /** Queued */
            queued: number;
            /** Message */
            message: string;
        };
        /** RunItemListResponse */
        RunItemListResponse: {
            /** Items */
            items: components["schemas"]["RunItemResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** RunItemResponse */
        RunItemResponse: {
            /** Id */
            id: number;
            /** Url */
            url: string;
            /** Source Item Id */
            source_item_id: number | null;
            /** External Item Id */
            external_item_id: string | null;
            /** Title */
            title: string | null;
            status: components["schemas"]["ProcessingStatus"];
            /** Error Message */
            error_message: string | null;
            duplicate_reason: components["schemas"]["DuplicateReason"] | null;
            /** Image Id */
            image_id: number | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /**
             * Query
             * @description Original query
             */
            query: string;
            /**
             * Results
             * @description Search results
             */
            results?: components["schemas"]["SearchResult"][];
            /**
             * Total
             * @description Total matching results
             */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Search Time Ms
             * @description Search time in milliseconds
             */
            search_time_ms: number;
            /**
             * Index Version
             * @description Active index version
             */
            index_version?: string | null;
        };
        /** SearchResult */
        SearchResult: {
            /**
             * Id
             * @description Image ID
             */
            id: number;
            /**
             * Sha256
             * @description Image hash
             */
            sha256: string;
            /**
             * Score
             * @description Similarity score
             */
            score: number;
            /**
             * Url
             * @description Image URL
             */
            url?: string | null;
            /**
             * Caption
             * @description Generated caption
             */
            caption?: string | null;
            /**
             * Ocr Text
             * @description Extracted text from image
             */
            ocr_text?: string | null;
            /**
             * Width
             * @description Image width
             */
            width?: number | null;
            /**
             * Height
             * @description Image height
             */
            height?: number | null;
        };
        /** SourceDetailResponse */
        SourceDetailResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Adapter Key */
            adapter_key: string;
            adapter_config: components["schemas"]["MemeApiAdapterConfig"];
            /** Dataset */
            dataset: string | null;
            /** Schedule Cron */
            schedule_cron: string | null;
            /** Schedule Timezone */
            schedule_timezone: string;
            /** Max Items Per Run */
            max_items_per_run: number | null;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            stats: components["schemas"]["SourceStatsResponse"];
            /** Recent Runs */
            recent_runs: components["schemas"]["SourceRunResponse"][];
        };
        /**
         * SourceItemIngestState
         * @enum {string}
         */
        SourceItemIngestState: "ingested" | "deduped" | "failed" | "in_flight" | "unknown";
        /** SourceItemListResponse */
        SourceItemListResponse: {
            /** Items */
            items: components["schemas"]["SourceItemResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** State Counts */
            state_counts: {
                [key: string]: number;
            };
        };
        /** SourceItemResponse */
        SourceItemResponse: {
            /** Id */
            id: number;
            /** External Item Id */
            external_item_id: string;
            /** Title */
            title: string | null;
            raw_metadata: components["schemas"]["MemeApiRawMetadata"] | null;
            /** Thumbnail Url */
            thumbnail_url: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            ingest_state: components["schemas"]["SourceItemIngestState"];
            /** Resolved Image Id */
            resolved_image_id: number | null;
            duplicate_reason: components["schemas"]["DuplicateReason"] | null;
            /** Duplicate Of Image Id */
            duplicate_of_image_id: number | null;
            attempt_status: components["schemas"]["ProcessingStatus"] | null;
            /** Attempt Error Message */
            attempt_error_message: string | null;
            /** Attempt Source Run Id */
            attempt_source_run_id: number | null;
            /** Media Url */
            media_url: string | null;
        };
        /** SourceListItemResponse */
        SourceListItemResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Adapter Key */
            adapter_key: string;
            adapter_config: components["schemas"]["MemeApiAdapterConfig"];
            /** Dataset */
            dataset: string | null;
            /** Schedule Cron */
            schedule_cron: string | null;
            /** Schedule Timezone */
            schedule_timezone: string;
            /** Max Items Per Run */
            max_items_per_run: number | null;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            stats: components["schemas"]["SourceStatsResponse"];
        };
        /** SourceListResponse */
        SourceListResponse: {
            /** Sources */
            sources: components["schemas"]["SourceListItemResponse"][];
            /** Total */
            total: number;
        };
        /** SourceResponse */
        SourceResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Adapter Key */
            adapter_key: string;
            adapter_config: components["schemas"]["MemeApiAdapterConfig"];
            /** Dataset */
            dataset: string | null;
            /** Schedule Cron */
            schedule_cron: string | null;
            /** Schedule Timezone */
            schedule_timezone: string;
            /** Max Items Per Run */
            max_items_per_run: number | null;
            /** Enabled */
            enabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SourceRunResponse */
        SourceRunResponse: {
            /** Id */
            id: number;
            trigger_mode: components["schemas"]["SourceRunTrigger"];
            status: components["schemas"]["SourceRunStatus"];
            /** Ingest Job Id */
            ingest_job_id: string | null;
            /** Error Message */
            error_message: string | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Discovered */
            discovered: number;
            /** Queued */
            queued: number;
            /** Duplicate */
            duplicate: number;
            /** Failed */
            failed: number;
        };
        /**
         * SourceRunStatus
         * @enum {string}
         */
        SourceRunStatus: "PENDING" | "RUNNING" | "COMPLETED" | "FAILED" | "PARTIAL";
        /**
         * SourceRunTrigger
         * @enum {string}
         */
        SourceRunTrigger: "scheduled" | "manual";
        /** SourceStatsResponse */
        SourceStatsResponse: {
            /** Run Count */
            run_count: number;
            /** Items Discovered */
            items_discovered: number;
            /** Duplicate Count */
            duplicate_count: number;
            /** Images Ingested */
            images_ingested: number;
            /** Failed Count */
            failed_count: number;
        };
        /** TriggerRunResponse */
        TriggerRunResponse: {
            /** Workflow Id */
            workflow_id: string;
            /** Message */
            message: string;
        };
        /** UpdateSourceRequest */
        UpdateSourceRequest: {
            adapter_config?: components["schemas"]["MemeApiAdapterConfig"] | null;
            /** Dataset */
            dataset?: string | null;
            /** Schedule Cron */
            schedule_cron?: string | null;
            /**
             * Schedule Timezone
             * @default UTC
             */
            schedule_timezone: string;
            /** Max Items Per Run */
            max_items_per_run?: number | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    check_readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                limit?: number;
                offset?: number;
                /** @description Optional mode. Omit for image search; use 'hybrid' to fuse image and text indexes. */
                mode?: "hybrid" | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    find_similar_search_similar__image_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                image_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_images_images_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: components["schemas"]["ImageStatus"] | null;
                dataset?: string | null;
                sort?: "newest" | "oldest";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageListResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    ingest_images_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageIngestResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    upload_image_images_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_images_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageIngestResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_image_images__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    delete_image_images__image_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    trigger_rebuild_index_jobs_rebuild_index_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RebuildIndexRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"] | null;
                job_type?: components["schemas"]["JobType"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_index_versions_jobs_indexes_versions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexVersionsResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_sources_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceListResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    create_source_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_source_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetailResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    delete_source_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    update_source_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    trigger_source_run_sources__source_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerRunResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    retry_source_sources__source_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    retry_source_run_sources__source_id__runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    retry_source_item_sources__source_id__items__item_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: number;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetryResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_source_items_sources__source_id__items_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: components["schemas"]["SourceItemIngestState"] | null;
            };
            header?: never;
            path: {
                source_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceItemListResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_run_items_sources__source_id__runs__run_id__items_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                source_id: number;
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunItemListResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    list_ingestion_ingestion_get: {
        parameters: {
            query?: {
                view?: components["schemas"]["IngestionView"];
                stage?: components["schemas"]["IngestStage"] | null;
                trigger?: components["schemas"]["SourceRunTrigger"] | null;
                source_id?: number | null;
                dataset?: string | null;
                outcome?: components["schemas"]["IngestOutcome"] | null;
                created_from?: string | null;
                created_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionListResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_ingestion_attempt_ingestion__ingest_url_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingest_url_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionDetailResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    get_ingestion_logs_ingestion__ingest_url_id__logs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                ingest_url_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionLogsResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
}
