"""add source registry tables

Revision ID: b745c57e8993
Revises: e71941847b1f
Create Date: 2026-06-10 20:07:16.074763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b745c57e8993'
down_revision: Union[str, Sequence[str], None] = 'e71941847b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Named so they are droppable on downgrade (anonymous FKs can't be dropped by name).
FK_INGEST_URLS_SOURCE = "fk_ingest_urls_source_id_ingestion_sources"
FK_INGEST_URLS_SOURCE_RUN = "fk_ingest_urls_source_run_id_source_runs"
FK_INGEST_URLS_SOURCE_ITEM = "fk_ingest_urls_source_item_id_source_items"

# Postgres enum type names backing the new StrEnum columns. create_table emits
# CREATE TYPE for these automatically; downgrade must drop them by hand or a
# re-upgrade collides with the leftover types.
SOURCE_ENUMS = ("sourcetype", "sourceruntrigger", "sourcerunstatus")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('API', name='sourcetype'), nullable=False),
    sa.Column('adapter_key', sa.String(length=100), nullable=False),
    sa.Column('adapter_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dataset', sa.String(length=255), nullable=True),
    sa.Column('schedule_cron', sa.String(length=255), nullable=True),
    sa.Column('schedule_timezone', sa.String(length=64), nullable=False),
    sa.Column('max_items_per_run', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Name is unique only among live Sources; a soft-deleted (deleted_at set)
    # Source frees its name for reuse.
    op.create_index(
        'uq_ingestion_sources_name_live',
        'ingestion_sources',
        ['name'],
        unique=True,
        postgresql_where=sa.text('deleted_at IS NULL'),
    )
    op.create_table('source_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('trigger_mode', sa.Enum('SCHEDULED', 'MANUAL', name='sourceruntrigger'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL', name='sourcerunstatus'), nullable=False),
    sa.Column('ingest_job_id', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingest_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_runs_source_id_created_at', 'source_runs', ['source_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_source_runs_status', 'source_runs', ['status'], unique=False)
    op.create_table('source_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('last_source_run_id', sa.Integer(), nullable=True),
    sa.Column('external_item_id', sa.Text(), nullable=False),
    sa.Column('canonical_item_url', sa.Text(), nullable=True),
    sa.Column('canonical_image_url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_source_run_id'], ['source_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['ingestion_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_item_id', name='uq_source_items_source_external')
    )
    op.create_index(op.f('ix_source_items_last_source_run_id'), 'source_items', ['last_source_run_id'], unique=False)
    op.create_index('ix_source_items_source_id', 'source_items', ['source_id'], unique=False)
    op.add_column('ingest_urls', sa.Column('source_id', sa.Integer(), nullable=True))
    op.add_column('ingest_urls', sa.Column('source_run_id', sa.Integer(), nullable=True))
    op.add_column('ingest_urls', sa.Column('source_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(FK_INGEST_URLS_SOURCE_ITEM, 'ingest_urls', 'source_items', ['source_item_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(FK_INGEST_URLS_SOURCE_RUN, 'ingest_urls', 'source_runs', ['source_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(FK_INGEST_URLS_SOURCE, 'ingest_urls', 'ingestion_sources', ['source_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(FK_INGEST_URLS_SOURCE, 'ingest_urls', type_='foreignkey')
    op.drop_constraint(FK_INGEST_URLS_SOURCE_RUN, 'ingest_urls', type_='foreignkey')
    op.drop_constraint(FK_INGEST_URLS_SOURCE_ITEM, 'ingest_urls', type_='foreignkey')
    op.drop_column('ingest_urls', 'source_item_id')
    op.drop_column('ingest_urls', 'source_run_id')
    op.drop_column('ingest_urls', 'source_id')
    op.drop_index('ix_source_items_source_id', table_name='source_items')
    op.drop_index(op.f('ix_source_items_last_source_run_id'), table_name='source_items')
    op.drop_table('source_items')
    op.drop_index('ix_source_runs_status', table_name='source_runs')
    op.drop_index('ix_source_runs_source_id_created_at', table_name='source_runs')
    op.drop_table('source_runs')
    op.drop_index('uq_ingestion_sources_name_live', table_name='ingestion_sources')
    op.drop_table('ingestion_sources')
    # create_table emitted CREATE TYPE for these; drop them so a re-upgrade
    # doesn't collide with the leftover enum types.
    for enum_name in SOURCE_ENUMS:
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
