"""enforce processing status enums

Revision ID: c05d42b69c83
Revises: 257d1eee7da8
Create Date: 2026-02-06 13:18:00.526406

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c05d42b69c83'
down_revision: str | Sequence[str] | None = '257d1eee7da8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE processing SET ocr_status = 'PENDING' WHERE ocr_status IS NULL")
    op.execute("UPDATE processing SET caption_status = 'PENDING' WHERE caption_status IS NULL")
    op.execute("UPDATE processing SET embed_status = 'PENDING' WHERE embed_status IS NULL")

    op.alter_column('processing', 'ocr_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='processingstatus'),
               postgresql_using='ocr_status::processingstatus',
               nullable=False)
    op.alter_column('processing', 'caption_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='processingstatus'),
               postgresql_using='caption_status::processingstatus',
               nullable=False)
    op.alter_column('processing', 'embed_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='processingstatus'),
               postgresql_using='embed_status::processingstatus',
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('processing', 'embed_status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='processingstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('processing', 'caption_status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='processingstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('processing', 'ocr_status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', name='processingstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
