from mimeme.activities.indexing import (
    build_index_activity,
    garbage_collect_indexes_activity,
    swap_index_activity,
)
from mimeme.activities.ingestion import (
    discover_and_queue_activity,
    fail_source_run_activity,
    fetch_source_activity,
    finalize_source_run_activity,
    start_source_run_activity,
)
from mimeme.activities.storage import (
    cleanup_staged_upload_activity,
    cleanup_temp_file_activity,
    download_image_activity,
    process_image_activity,
)
from mimeme.activities.workflow_state import (
    complete_ingest_job_activity,
    complete_rebuild_job_activity,
    fail_rebuild_job_activity,
    ingest_initialize_activity,
    mark_ingest_url_done_activity,
    mark_ingest_url_failed_activity,
    prepare_rebuild_activity,
    reconcile_generation_activity,
    record_ingest_stage_activity,
    release_rebuild_claim_activity,
    save_annotations_activity,
    save_embedding_info_activity,
    start_rebuild_job_activity,
    update_job_progress_activity,
)

ACTIVITIES = [
    start_source_run_activity,
    fetch_source_activity,
    discover_and_queue_activity,
    finalize_source_run_activity,
    fail_source_run_activity,
    download_image_activity,
    cleanup_staged_upload_activity,
    process_image_activity,
    cleanup_temp_file_activity,
    build_index_activity,
    swap_index_activity,
    garbage_collect_indexes_activity,
    ingest_initialize_activity,
    mark_ingest_url_failed_activity,
    mark_ingest_url_done_activity,
    record_ingest_stage_activity,
    save_annotations_activity,
    save_embedding_info_activity,
    update_job_progress_activity,
    complete_ingest_job_activity,
    prepare_rebuild_activity,
    reconcile_generation_activity,
    release_rebuild_claim_activity,
    start_rebuild_job_activity,
    fail_rebuild_job_activity,
    complete_rebuild_job_activity,
]


__all__ = [
    "ACTIVITIES",
    "start_source_run_activity",
    "fetch_source_activity",
    "discover_and_queue_activity",
    "finalize_source_run_activity",
    "fail_source_run_activity",
    "download_image_activity",
    "cleanup_staged_upload_activity",
    "process_image_activity",
    "cleanup_temp_file_activity",
    "build_index_activity",
    "swap_index_activity",
    "garbage_collect_indexes_activity",
    "ingest_initialize_activity",
    "mark_ingest_url_failed_activity",
    "mark_ingest_url_done_activity",
    "record_ingest_stage_activity",
    "save_annotations_activity",
    "save_embedding_info_activity",
    "update_job_progress_activity",
    "complete_ingest_job_activity",
    "prepare_rebuild_activity",
    "reconcile_generation_activity",
    "release_rebuild_claim_activity",
    "start_rebuild_job_activity",
    "fail_rebuild_job_activity",
    "complete_rebuild_job_activity",
]
