"""Initial schema with images, processing, annotations, artifacts, and index_builds tables

Revision ID: 7b620cf182c8
Revises: 
Create Date: 2025-12-29 21:45:43.228915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b620cf182c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('dataset', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('s3_key', sa.Text(), nullable=True),
    sa.Column('s3_etag', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('phash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index(op.f('ix_images_dataset'), 'images', ['dataset'], unique=False)
    op.create_index(op.f('ix_images_phash'), 'images', ['phash'], unique=False)
    op.create_table('index_builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=True),
    sa.Column('embed_model', sa.Text(), nullable=True),
    sa.Column('index_type', sa.String(length=20), nullable=True),
    sa.Column('num_vectors', sa.Integer(), nullable=True),
    sa.Column('dimension', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('annotations',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('caption_text', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('artifacts',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', 'kind', 'model_version'),
    sa.UniqueConstraint('image_id', 'kind', 'model_version', name='uq_artifacts_image_kind_version')
    )
    op.create_table('processing',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('ocr_status', sa.String(length=20), nullable=True),
    sa.Column('ocr_model', sa.Text(), nullable=True),
    sa.Column('ocr_updated_at', sa.DateTime(), nullable=True),
    sa.Column('caption_status', sa.String(length=20), nullable=True),
    sa.Column('caption_model', sa.Text(), nullable=True),
    sa.Column('caption_updated_at', sa.DateTime(), nullable=True),
    sa.Column('embed_status', sa.String(length=20), nullable=True),
    sa.Column('embed_model', sa.Text(), nullable=True),
    sa.Column('embed_dim', sa.Integer(), nullable=True),
    sa.Column('embed_updated_at', sa.DateTime(), nullable=True),
    sa.Column('embed_s3_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing')
    op.drop_table('artifacts')
    op.drop_table('annotations')
    op.drop_table('index_builds')
    op.drop_index(op.f('ix_images_phash'), table_name='images')
    op.drop_index(op.f('ix_images_dataset'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
