"""Convert timestamp fields to DateTime

Revision ID: d192c4d2a51f
Revises: 
Create Date: 2025-11-29 14:41:13.287740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd192c4d2a51f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('kind',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('model_version',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_unique_constraint('uq_artifacts_image_kind_version', ['image_id', 'kind', 'model_version'])

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('index_builds', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('processing', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('ocr_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('ocr_updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('caption_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('caption_updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('embed_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('embed_updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing', schema=None) as batch_op:
        batch_op.alter_column('embed_updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('embed_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('caption_updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('caption_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('ocr_updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ocr_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('index_builds', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_artifacts_image_kind_version', type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('model_version',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('kind',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.alter_column('image_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
